export const _pos = [
  {
    nodeId: 1,
    x: 700,
    y: 50,
  },
  {
    nodeId: 2,
    x: 700,
    y: 150,
  },
  {
    nodeId: 3,
    x: 700,
    y: 500,
  },
  {
    nodeId: 4,
    x: 700,
    y: 500,
  },
  {
    nodeId: 5,
    x: 700,
    y: 500,
  },
  {
    nodeId: 6,
    x: 700,
    y: 500,
  },
  {
    nodeId: 7,
    x: 700,
    y: 500,
  },
  {
    nodeId: 8,
    x: 700,
    y: 500,
  },
  {
    nodeId: 9,
    x: 700,
    y: 500,
  },
  {
    nodeId: 10,
    x: 700,
    y: 500,
  },
  {
    nodeId: 11,
    x: 700,
    y: 500,
  },
  {
    nodeId: 12,
    x: 700,
    y: 500,
  },
  {
    nodeId: 13,
    x: 700,
    y: 500,
  },
  {
    nodeId: 14,
    x: 700,
    y: 500,
  },
  {
    nodeId: 15,
    x: 700,
    y: 500,
  },
  {
    nodeId: 16,
    x: 700,
    y: 500,
  },
  {
    nodeId: 17,
    x: 700,
    y: 500,
  },
  {
    nodeId: 18,
    x: 700,
    y: 500,
  },
  {
    nodeId: 19,
    x: 700,
    y: 500,
  },
  {
    nodeId: 20,
    x: 700,
    y: 500,
  },
  {
    nodeId: 21,
    x: 700,
    y: 500,
  },
  {
    nodeId: 22,
    x: 700,
    y: 500,
  },
];

export const result = {
  carePathId: 1,
  description: "AMI Care Path",
  organizationId: 1,
  modelId: 1,
  nodeList: [
    {
      nodeId: 16,
      description: "Complete hsTnl at 4-hour",
      expression: "0",
      expressionValue: null,
      parentNodes: ["15"],
      childIdNodes: ["17", "14"],
      style: '{"bgcolor":"yellow","color": "black"}',
    },
    {
      nodeId: 17,
      description: "30 day MACE probability after 4 order",
      expression: "0",
      expressionValue: null,
      parentNodes: ["16"],
      childIdNodes: ["18", "19"],
      style: '{"bgcolor":"yellow","color": "black"}',
    },
    {
      nodeId: 18,
      description: "< or = 1 % Discharge w/ PCP follow-up",
      expression: "<=",
      expressionValue: "1%",
      parentNodes: ["17"],
      childIdNodes: ["0"],
      style: '{"bgcolor":"yellow","color": "black"}',
    },
    {
      nodeId: 19,
      description: "> 1 % Place on Medical Service",
      expression: ">",
      expressionValue: "1%",
      parentNodes: ["17"],
      childIdNodes: ["0"],
      style: '{"bgcolor":"yellow","color": "black"}',
    },
    {
      nodeId: 20,
      description: "< or = 1 % Discharge w/ PCP follow-up",
      expression: "<=",
      expressionValue: "1%",
      parentNodes: ["9"],
      childIdNodes: ["0"],
      style: '{"bgcolor":"forestgreen","color": "lightgrey"}',
    },
    {
      nodeId: 21,
      description: "1-5 % Dischacarge w/ next day cardiology consultation ",
      expression: "between",
      expressionValue: "1,5%",
      parentNodes: ["9"],
      childIdNodes: ["0"],
      style: '{"bgcolor":"forestgreen","color": "lightgrey"}',
    },
    {
      nodeId: 22,
      description: "> 5 % Place on Medical Service",
      expression: ">",
      expressionValue: "5%",
      parentNodes: ["9"],
      childIdNodes: ["0"],
      style: '{"bgcolor":"forestgreen","color": "lightgrey"}',
    },
    {
      nodeId: 1,
      description:
        "Complains of chest pain or symptoms of Acute Coronary Syndrome",
      expression: null,
      expressionValue: null,
      parentNodes: ["0"],
      childIdNodes: ["2"],
      style: '{"bgcolor":"steelblue","color": "lightgrey"}',
    },
    {
      nodeId: 2,
      description:
        "ECG completed and reviewed by a physician within 10 minutes, repeat ECG for new or increased chest pain;Vital signs; Identify onset of symptoms",
      expression: null,
      expressionValue: null,
      parentNodes: ["1"],
      childIdNodes: ["3", "4"],
      style: '{"bgcolor":"steelblue","color": "lightgrey"}',
    },
    {
      nodeId: 3,
      description: "See STEMI flowchart",
      expression: null,
      expressionValue: null,
      parentNodes: ["2"],
      childIdNodes: ["0"],
      style: '{"bgcolor":"steelblue","color": "lightgrey"}',
    },
    {
      nodeId: 4,
      description:
        "Monitor bed, IV access, Consider: Oxygen, history and physical exam, CXR, and high sensitivity Troponin | (hs cTnl) now",
      expression: null,
      expressionValue: null,
      parentNodes: ["2"],
      childIdNodes: ["5"],
      style: '{"bgcolor":"steelblue","color": "lightgrey"}',
    },
    {
      nodeId: 5,
      description: "0 hour hsTnl",
      expression: null,
      expressionValue: null,
      parentNodes: ["4"],
      childIdNodes: ["6", "7", "8"],
      style: '{"bgcolor":"steelblue","color": "lightgrey"}',
    },
    {
      nodeId: 6,
      description: "<5 ng/L",
      expression: "< ",
      expressionValue: "5",
      parentNodes: ["5"],
      childIdNodes: ["9", "10"],
      style: '{"bgcolor":"steelblue","color": "lightgrey"}',
    },
    {
      nodeId: 7,
      description: "5-49 ng/L",
      expression: "between",
      expressionValue: "5,49",
      parentNodes: ["5"],
      childIdNodes: ["10"],
      style: '{"bgcolor":"yellow","color": "black"}',
    },
    {
      nodeId: 8,
      description: ">= 50 ng/L",
      expression: ">=",
      expressionValue: "50",
      parentNodes: ["5", "10"],
      childIdNodes: ["11"],
      style: '{"bgcolor":"firebrick","color": "lightgrey"}',
    },
    {
      nodeId: 9,
      description: "30-day MACE probability",
      expression: "0",
      expressionValue: null,
      parentNodes: ["6", "12"],
      childIdNodes: ["20", "21", "22"],
      style: '{"bgcolor":"forestgreen","color": "lightgrey"}',
    },
    {
      nodeId: 10,
      description: "Complete hsTnl at 2-hour",
      expression: "0",
      expressionValue: null,
      parentNodes: ["6", "7"],
      childIdNodes: ["12", "13", "14"],
      style: '{"bgcolor":"yellow","color": "black"}',
    },
    {
      nodeId: 11,
      description: "Rule In and Admit patient",
      expression: "0",
      expressionValue: null,
      parentNodes: ["8", "14"],
      childIdNodes: ["0"],
      style: '{"bgcolor":"firebrick","color": "lightgrey"}',
    },
    {
      nodeId: 12,
      description: "Delta < 5 ng/L at 2-hour",
      expression: "delta <",
      expressionValue: "5",
      parentNodes: ["10"],
      childIdNodes: ["9"],
      style: '{"bgcolor":"forestgreen","color": "lightgrey"}',
    },
    {
      nodeId: 13,
      description: "Delta < 5-19 ng/L at 2-hour",
      expression: "delta between",
      expressionValue: "5,19",
      parentNodes: ["10"],
      childIdNodes: ["15"],
      style: '{"bgcolor":"yellow","color": "black"}',
    },
    {
      nodeId: 14,
      description: "Delta > 20 ng/L at 2-hour",
      expression: "delta >",
      expressionValue: "20",
      parentNodes: ["10", "16"],
      childIdNodes: ["11"],
      style: '{"bgcolor":"firebrick","color": "lightgrey"}',
    },
    {
      nodeId: 15,
      description: "Consultation with medicine service",
      expression: "0",
      expressionValue: null,
      parentNodes: ["13"],
      childIdNodes: ["16"],
      style: '{"bgcolor":"yellow","color": "black"}',
    },
  ],
  patientPosition: {
    nodeId: 19,
    description: "> 1 % Place on Medical Service",
    expression: ">",
    expressionValue: "1%",
    parentNodes: ["17"],
    childIdNodes: ["0"],
    style: '{"bgcolor":"yellow","color": "black"}',
  },
};

const elements = [
  {
    id: "1",
    type: "input", // input node
    data: { label: "Input Node" },
    position: { x: 250, y: 25 },
    draggable: false,
    connectable: false,
    style: {
      background: "red",
    },
  },
  // default node
  {
    id: "2",
    // you can also pass a React component as a label
    data: { label: <div>Default Node</div> },
    position: { x: 100, y: 125 },
    draggable: false,
    connectable: false,
  },
  {
    id: "3",
    type: "output", // output node
    data: { label: "Output Node" },
    position: { x: 250, y: 250 },
    draggable: false,
    connectable: false,
  },
  // animated edge
  { id: "e1-2", source: "1", target: "2" },
  { id: "e1-3", source: "1", target: "3" },
];
